---
title: "ProyectoTD2026"
author: "Sofia Rivera Vidal"
date: "2026-03-31"
output:
  bookdown::pdf_document2:
    fig_caption: yes
    df_print: kable
  bookdown::html_document2:
    fig_caption: yes
    df_print: kable
lang: es
header-includes:
  - \usepackage{graphicx}
  - \usepackage{fancyhdr}
  - \usepackage{caption}
  - \addto\captionsspanish{\renewcommand{\tablename}{Tabla}}
  - \pagestyle{fancy}
  - \fancyhf{}
  - \renewcommand{\headrulewidth}{0.5pt}
  - \renewcommand{\footrulewidth}{0.4pt}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(ggplot2)
```


```{r}
library(tidyverse)
library(lubridate)
#Carga de datos
data <- read_csv("data/logs_moodle_anon.csv")

#Corrección de la columna "Hora" para que tenga formato. División de esta en "Fecha" y "Hora".
data$Hora <- dmy_hms(data$Hora)
data <- data %>% mutate(Fecha = as_date(Hora)) %>% mutate(Hora = format(Hora, "%H:%M:%S"))
colnames(data)
data <- subset(data, select=c(10, 1:9))
View(data)

#Convertimos Hora a hms en lugar de caracter
library(hms)
data$Hora <- as_hms(data$Hora)

```

```{r figura-eventos, fig.cap = "Distribución de eventos por hora del día"}
library(lubridate)
data %>% 
  mutate(hora_dia = hour(Hora)) %>%
  count(hora_dia) %>%
  ggplot(aes(hora_dia, n)) + geom_bar(stat = "identity", fill = "red") +
  labs(title = "EVENTOS POR HORA DEL DÍA",
       x = "Hora del Dia(0-23)",
       y = "Numero de Eventos",
       caption = "La hora del día con más eventos es a las 9:00 con más de 15000 eventos")

```

En la Figura \@ref(fig:figura-eventos) se puede observar la distribución de eventos a lo largo del día, donde destaca una mayor actividad durante las horas de la mañana, especialmente a las 9:00.



